[tool.ruff]
line-length = 120
target-version = "py38"
exclude = ["__init__.py"]
fix = true

[tool.ruff.lint]
ignore = [
    # "W191",  # indentation contains tabs
    "B008", # function call in default argument
]
select = [
    "E",  # Pyflakes errors
    "W",  # Pyflakes warnings
    "F",  # Pyflakes errors
    "I",  # isort
    "C",  # flake8-comprehensions
    "B",  # flake8-bugbear
    "UP", # pyupgrade
]

[tool.ruff.format]
quote-style = "single"
# indent-style = "tab"
docstring-code-format = true

[tool.pylint.main]
load-plugins = ["pylint_sqlalchemy"]

[tool.poetry]
packages = [{ include = "src" }]
[project]
name = "rssa-api"
version = "0.5.0"
description = "Web API for the Recommender Systems for Self Actualization project."
authors = [{ name = "Mehtab 'Shahan' Iqbal", email = "mehtabi@clemson.edu" }]
license = { text = "MIT License" }
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi (>=0.118.0,<0.119.0)",
    "sqlalchemy (>=2.0.43,<3.0.0)",
    "uvicorn (>=0.37.0,<0.38.0)",
    "lenskit (>=2025.2.0,<2026.0.0)",
    "httpx (>=0.28.1,<0.29.0)",
    "async-lru (>=2.0.5,<3.0.0)",
    "python-jose[cryptography] (>=3.5.0,<4.0.0)",
    "dotenv (>=0.9.9,<0.10.0)",
    "asyncpg (>=0.30.0,<0.31.0)",
    "binpickle (>=0.3.4,<0.4.0)",
    "annoy (>=1.17.3,<2.0.0)",
    "joblib (>=1.5.2,<2.0.0)",
    "scikit-learn (>=1.7.2,<2.0.0)",
]

[dependency-groups]
dev = ["pytest (>=8.4.2,<9.0.0)", "ruff (>=0.13.3,<0.14.0)"]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
