[tool.ruff]
line-length = 120
target-version = "py38"
exclude = ["__init__.py"]
fix = true

[tool.ruff.lint]
ignore = [
	# "W191",  # indentation contains tabs
	"B008", # function call in default argument
]
select = [
	"E",  # Pyflakes errors
	"W",  # Pyflakes warnings
	"F",  # Pyflakes errors
	"I",  # isort
	"C",  # flake8-comprehensions
	"B",  # flake8-bugbear
	"UP", # pyupgrade
]

[tool.ruff.format]
quote-style = "single"
# indent-style = "tab"
docstring-code-format = true

[tool.pylint.main]
load-plugins = ["pylint_sqlalchemy"]

[tool.setuptools]
packages = ["src"]